from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1172, 685)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 1151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 1151, 571))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lblBar = QtWidgets.QLabel(self.layoutWidget)
        self.lblBar.setObjectName("lblBar")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.lblBar)
        self.spnBar = QtWidgets.QSpinBox(self.layoutWidget)
        self.spnBar.setObjectName("spnBar")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.spnBar)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.btnScramble = QtWidgets.QPushButton(self.layoutWidget)
        self.btnScramble.setObjectName("btnScramble")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.btnScramble)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(8, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(10, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(12, QtWidgets.QFormLayout.LabelRole, spacerItem5)
        self.btnSelectionSort = QtWidgets.QPushButton(self.layoutWidget)
        self.btnSelectionSort.setObjectName("btnSelectionSort")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.SpanningRole, self.btnSelectionSort)
        self.btnMergeSort = QtWidgets.QPushButton(self.layoutWidget)
        self.btnMergeSort.setObjectName("btnMergeSort")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.btnMergeSort)
        self.btnBubbleSort = QtWidgets.QPushButton(self.layoutWidget)
        self.btnBubbleSort.setObjectName("btnBubbleSort")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.btnBubbleSort)
        self.btnInsertionSort = QtWidgets.QPushButton(self.layoutWidget)
        self.btnInsertionSort.setObjectName("btnInsertionSort")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.btnInsertionSort)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout)
        self.widGraph = QtWidgets.QWidget(self.layoutWidget)
        self.widGraph.setObjectName("widGraph")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.widGraph)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1172, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sort And Shuffle"))
        self.label.setText(_translate("MainWindow", "Sort"))
        self.lblBar.setText(_translate("MainWindow", "Number of bars"))
        self.btnScramble.setText(_translate("MainWindow", "Scramble"))
        self.btnSelectionSort.setText(_translate("MainWindow", "Selection Sort"))
        self.btnMergeSort.setText(_translate("MainWindow", "Merge Sort"))
        self.btnBubbleSort.setText(_translate("MainWindow", "Bubble Sort"))
        self.btnInsertionSort.setText(_translate("MainWindow", "Insertion Sort"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
